name: Build executables for release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    name: Build Windows EXE
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod download

      - name: Build executable
        run: |
          go build -v -o ethcrawler_winx64.exe .
          echo "Built ethcrawler for Windows"

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: ethcrawler-windows
          path: ethcrawler_winx64.exe

  build-linux:
    name: Build Linux binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod download

      - name: Build Linux binary
        run: |
          go build -v -o ethcrawler_linux64 .
          echo "Built ethcrawler for Linux"

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: ethcrawler-linux
          path: ethcrawler_linux64

  build-macos-arm:
    name: Build macOS ARM binary
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod download

      - name: Build macOS binary
        env:
          GOOS: darwin
          GOARCH: arm64
        run: |
          go build -v -o ethcrawler_macos_arm .
          echo "Built ethcrawler for macOS ARM"

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: ethcrawler-macos-arm
          path: ethcrawler_macos_arm

  release:
    name: Create GitHub Release
    needs: [build-windows, build-linux, build-macos-arm]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ethcrawler-windows/ethcrawler_winx64.exe
            ethcrawler-linux/ethcrawler_linux64
            ethcrawler-macos-arm/ethcrawler_macos_arm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 